# Generated by Django 3.1.7 on 2021-03-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210308_0313'),
        ('users', '0004_auto_20210308_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stores',
        ),
        migrations.AddField(
            model_name='profile',
            name='stores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
