# Generated by Django 3.1.7 on 2021-03-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210308_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stores',
            new_name='store',
        ),
    ]
